#pragma once

#include "../../src/Renderer/Scene/Entities/SkyboxEntity.h"
#include "../src/Assets/AssetImporter.h"
#include "../src/Assets/KAsset.h"
#include "../src/Core/Engine.h"
#include "../src/Core/Logger.h"
#include "../src/Core/Time.h"
#include "../src/Event/Event.h"
#include "../src/Event/EventManager.h"
#include "../src/Event/KeyboardEvents.h"
#include "../src/Event/MouseEvents.h"
#include "../src/Event/WindowEvents.h"
#include "../src/File/FileReader.h"
#include "../src/Input/Input.h"
#include "../src/Input/InputKeys.h"
#include "../src/Instances/IGameInstance.h"
#include "../src/Renderer/Renderer.h"
#include "../src/Renderer/RendererAPI.h"
#include "../src/Renderer/Buffers/FrameBuffer.h"
#include "../src/Renderer/Buffers/IndexBuffer.h"
#include "../src/Renderer/Buffers/RenderBuffer.h"
#include "../src/Renderer/Buffers/ShaderStorageBuffer.h"
#include "../src/Renderer/Buffers/UniformBuffer.h"
#include "../src/Renderer/Buffers/VertexArray.h"
#include "../src/Renderer/Buffers/VertexBuffer.h"
#include "../src/Renderer/Scene/Components/Components.h"
#include "../src/Renderer/Scene/Camera.h"
#include "../src/Renderer/Scene/Entity.h"
#include "../src/Renderer/Scene/Scene.h"
#include "../src/Renderer/Scene/Transformation.h"
#include "../src/Renderer/Scene/Entities/LightEntity.h"
#include "../src/Renderer/Scene/Primitives/Material.h"
#include "../src/Renderer/Scene/Primitives/Mesh.h"
#include "../src/Renderer/Scene/Primitives/Model.h"
#include "../../src/Assets/Shader.h"
#include "../src/Renderer/Shaders/ShaderManager.h"
#include "../src/Renderer/Util/GeometryUtil.h"
#include "../src/Renderer/Util/PhongProperties.h"
#include "../src/Renderer/Util/Vertex.h"
#include "../../src/Assets/Texture.h"
#include "../src/Renderer/Textures/TextureManager.h"

#include "../src/Window/Window.h"


