#pragma once

#include "../src/Asset/AssetImporter.h"
#include "../src/Asset/KAsset.h"
#include "../src/Core/Engine.h"
#include "../src/Core/Logger.h"
#include "../src/Core/Time.h"
#include "../src/Events/EventManager.h"
#include "../src/Events/Event.h"
#include "../src/Events/WindowEvents.h"
#include "../src/Events/KeyboardEvents.h"
#include "../src/Events/MouseEvents.h"
#include "../src/File/FileReader.h"
#include "../src/Input/InputKeys.h"
#include "../src/Input/Input.h"
#include "../src/Instances/IGameInstance.h"
#include "../src/Renderer/Buffers/IndexBuffer.h"
#include "../src/Renderer/Buffers/VertexArray.h"
#include "../src/Renderer/Buffers/VertexBuffer.h"
#include "../src/Renderer/Buffers/UniformBuffer.h"
#include "../src/Renderer/Shaders/Shader.h"
#include "../src/Renderer/Shaders/ShaderManager.h"
#include "../src/Renderer/Structs/GeometryHelper.h"
#include "../src/Renderer/Structs/PhongProperties.h"
#include "../src/Renderer/Structs/Vertex.h"
#include "../src/Renderer/Textures/Texture.h"
#include "../src/Renderer/Textures/TextureManager.h"
#include "../src/Renderer/Renderer.h"
#include "../src/Renderer/RendererAPI.h"
#include "../src/Renderer/Scene/Scene.h"
#include "../src/Renderer/Scene/Camera.h"
#include "../src/Renderer/Scene/Entity.h"
#include "../src/Renderer/Scene/Transformation.h"
#include "../src/Renderer/Scene/Primitives/Mesh.h"
#include "../src/Renderer/Scene/Primitives/Material.h"
#include "../src/Renderer/Scene/Primitives/Model.h"

#include "../src/Window/Window.h"


